### ISSUE TITLE
[QUESTION] 源码呢？

### ISSUE THREAD

**Issue by MMitsuha** [7emotions/Autor#1]
ftz不放源码🤣

**Comment by 7emotions** [comment]
刚写好




Familiar&nbsp;stranger
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "7emotions/Autor"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Jan 21, 2023 03:11 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[7emotions/Autor] [QUESTION] 源码呢？ (Issue #1)





 
ftz不放源码🤣
